### ISSUE TITLE
Starting with 0 elements

### ISSUE THREAD

**Issue by digitaloutback** [DubFriend/jquery.repeater#10]
Is there a suggested way to start with 0 elements displaying, only the 'add' button?

**Comment by DubFriend** [comment]
I am pretty sure you should be able to remove the first data-repeater-item after calling the repeater method.

I was able to get this to work doing the following

```javascript
$('.repeater').repeater();
setTimeout(function () {
  $('.repeater').find('[data-repeater-item]').remove();
}, 0);
```
