### ISSUE TITLE
Drag & drop index re-ordering

### ISSUE THREAD

**Issue by alessandrotesoro** [DubFriend/jquery.repeater#11]
Hello,

Thanks for such useful plugin, it's very easy to use. In my current setup I have added the ability to drag & drop the repeater items and it works fine, the only issue is that the index is messed up. I've read the already closed issue https://github.com/DubFriend/jquery.repeater/issues/9 but I'm not able to understand how to call the reset index functionality from the drag & drop script.

I'm using jquery sortable for the drag and drop functionality: 

```
jQuery(".repeater-table").sortable({
    axis: "y",
    cursor: 'pointer',
    opacity: 0.5,
    placeholder: "row-dragging",
    delay: 150,
    handle: ".sort-option",
    update: function(event, ui) {
        // stuff to do on sorting update.
    }

}).disableSelection();
```

And this is the repeater function 

```
jQuery('.wpumcf-field-repeater-options').repeater({
    show: function() {
        jQuery(this).slideDown();

        jQuery('.repeater-wrapper').animate({
            scrollTop: jQuery('.repeater-table').height()
        }, 300);
    },
    hide: function(deleteElement) {
        if (confirm(wpum_admin_js.confirm)) {
            jQuery(this).slideUp(deleteElement);
        }
    },
    ready: function(setIndexes) {
        $dragAndDrop.on('drop', setIndexes);
    },
    isFirstItemUndeletable: true
});
```

Have you got any example on how to call the reset functionality from another script ? 

Thank you.

**Comment by alessandrotesoro** [comment]
I've modified my code this way 

```
var options_repeater = jQuery('.wpumcf-field-repeater-options');

			options_repeater.repeater({
					show: function () {
							jQuery(this).slideDown();

							jQuery('.repeater-wrapper').animate({
									scrollTop: jQuery('.repeater-table').height()
							}, 300);
					},
					hide: function ( deleteElement ) {
							if( confirm( wpum_admin_js.confirm ) ) {
									jQuery(this).slideUp( deleteElement );
							}
					},
					ready: function ( setIndexes ) {
							$dragAndDrop.on( 'drop', setIndexes );
					},
					isFirstItemUndeletable: true
			});

			jQuery(".repeater-table").sortable({
				axis: "y",
				cursor: 'pointer',
				opacity: 0.5,
				placeholder: "row-dragging",
				delay: 150,
				handle: ".sort-option",
				update: function(event, ui) {
					options_repeater.repeater( 'setIndexes' );
				}

			}).disableSelection();
```

It seems to correctly re-order the index of the items.

I've got a question, should the isFirstItemUndeletable option, also work once the items are re-indexed ?

**Comment by DubFriend** [comment]
Hmm, I would check to see if the "show" callback is being called twice, it looks like dom click events may be getting bound twice here:

```javascript
update: function(event, ui) {
    // I think this may be causing the problem. 
    // Calling repeater a second time here will rebind
    // click events. Now when clicking the "add" button, 
    // the click event to create a new item will
    // be called twice.
    options_repeater.repeater( 'setIndexes' );
}
```

$().repeater should only be called once on a set of dom elements.

**Comment by devilstars** [comment]
So... any solution?

https://codepen.io/Simushkin/pen/XqKeVQ issue is still here.

**Comment by fmonts** [comment]
@devilstars jquery functions like .serializeArray()?

**Comment by devilstars** [comment]
@fmonts same here. serializeArray() returns an empty array [].

I've updated https://codepen.io/Simushkin/pen/XqKeVQ with console logs. Atm i'm going to write a php parser of subimt request data to store it in correct order.

**Comment by fmonts** [comment]
setializeArray() must be done on the form:
https://codepen.io/anon/pen/jxaVWY

but I see your issue, it's because you've hardcoded the indexes, car[0], car[1], etc... 
There is no need to do it, if they have an ID you need to keep, you can create an hidden field

**Comment by fmonts** [comment]
maybe now I understand your issue, I fixed server side with array_values() to remove the indexes

**Comment by bilalmalkoc** [comment]
@devilstars 
Hello. Did you solve your issue?

Here is my snippet:
https://stackblitz.com/edit/js-pbdssq?file=index.js

**Comment by amrikarisma** [comment]
> Hmm, I would check to see if the "show" callback is being called twice. It looks like dom click events may be getting bound twice here:
> 
> ```js
> update: function(event, ui) {
>     // I think this may be causing the problem. 
>     // Calling repeater a second time here will rebind
>     // click events. Now when clicking the "add" button, 
>     // the click event to create a new item will
>     // be called twice.
>     options_repeater.repeater( 'setIndexes' );
> }
> ```
> 
> $().repeater should only be called once on a set of dom elements.

Thank you..

**Comment by DeeJ** [comment]
For anyone stumbling across this years later... Here some actual working code, slightly modified from above.

` // Javascript Repeater Variant
    $(document).ready(function() {

        const variantRepeat = $('.variant-repeater');
        const sortable = $(".sortable").sortable({
            update: function() {
                //variantRepeat.repeater( 'setIndexes' ); // Don't call this as it re-initializes the repeated and if you go to add a new repeating item you'll start to get multiple added at once

            }
        });

        variantRepeat.repeater({
            show: function () {
                $(this).slideDown();
                // Feather Icons
                if (feather) {
                feather.replace({ width: 14, height: 14 });
                }
            },
            hide: function (deleteElement) {
                if (confirm('Are you sure you want to delete this element?')) {
                $(this).slideUp(deleteElement);
                }
            },
            ready: function(setIndexes) {
                sortable.on("sortstop", setIndexes); // sortstop instead of sortchange
            }
        });
    });`

**Comment by fuadarradhi** [comment]
for anyone who wants to reindex after reorder, you can save setIndexes to a variable first so it can be reused after reorder
