### ISSUE TITLE
Can't get array value of multiple select

### ISSUE THREAD

**Issue by ihgs** [DubFriend/jquery.repeater#12]
Even when I use multiple select element which uses name as `name="names[]"`, I can't get array value from posted parameters.

I checked this element using chrome developer tool. `[]` was removed.

I think select[multiple] condition is needed in bellow line:
https://github.com/DubFriend/jquery.repeater/blob/master/jquery.repeater.js#L741-L742

**Comment by DubFriend** [comment]
Hey thanks I will look into this when I get time, probably this weekend :smile:

**Comment by ihgs** [comment]
Thank you for the modification and useful plugin.
