### ISSUE TITLE
deactivate first line deletion

### ISSUE THREAD

**Issue by ammimounir** [DubFriend/jquery.repeater#142]
How can I disable the possibility to delete the first set of form inputs (row) ?
the first row should always be there.

**Comment by SlavaSt295** [comment]
> How can I disable the possibility to delete the first set of form inputs (row) ?
> the first row should always be there.

isFirstItemUndeletable: true

**Comment by ammimounir** [comment]
> > How can I disable the possibility to delete the first set of form inputs (row) ?
> > the first row should always be there.
> 
> isFirstItemUndeletable: true

thanks man !
