### ISSUE TITLE
How I can set Unique id or value to a repeter input

### ISSUE THREAD

**Issue by hiteshsubnani0128** [DubFriend/jquery.repeater#143]
I am trying to add an unique id to a repeater input.

**Comment by arikod** [comment]
I am using repeater. My inputs are created in the form of an array, this is great. But how can I make the a tag in the repeater and the ids of the inputs to be similar

**Comment by arikod** [comment]
> I am trying to add an unique id to a repeater input.

I am using repeater. My inputs are created in the form of an array, this is great. But how can I make the a tag in the repeater and the ids of the inputs to be similar
