### ISSUE TITLE
Input type number does not support

### ISSUE THREAD

**Issue by bishwajitcadhikary** [DubFriend/jquery.repeater#158]
`<input type="number" name="money"/>`
does not return value

**Comment by pravnkay** [comment]
For this to work, 

You can set the type to `text` and also have a data attribute on your number input fields like, `data-convert` marking them to be converted to number type.

````html
<input type="text" data-input="convert" />
````

Once the repeater is initialized, under the `show` property you can convert them all back to `number` type like,

````js
$('.repeater').repeater({
  initEmpty: true,
  show: function () {
    // changing the manual input fields of number type to number type from text
    repeater.find('input[data-input="convert"]').removeAttr('type').attr('type',"number")

    //continue...
````

At least, that's how I do it for now.
