### ISSUE TITLE
Function to reset to original state?

### ISSUE THREAD

**Issue by digitaloutback** [DubFriend/jquery.repeater#17]
Is there a recommended way to reset the DOM to original state? (remove additional, repeated items)

**Comment by DubFriend** [comment]
jquery.repeater does not keep track of the initial dom state, so the library would be unable to help here.

If what you want is to revert to a single blank item in the list, you might see if this works.

```javascript
$('[data-repeater-list]').empty();
$('[data-repeater-create]').click();
```

**Comment by humming-soft** [comment]
$('[data-repeater-item]').slice(1).empty();

**Comment by sebint** [comment]
This worked for me : 
`$('[data-repeater-item]').slice(1).empty();`

**Comment by juneX05** [comment]
> This worked for me :
> `$('[data-repeater-item]').slice(1).empty();`

This currently leaves extra spaces on the form.

May be we can try use this as a modification. Though am not so sure of the effects but we can use it as a work around for the mean time.

$('[data-repeater-item]').slice(1).remove();
