### ISSUE TITLE
Is it possible to dynamicly add data

### ISSUE THREAD

**Issue by Xanvier54** [DubFriend/jquery.repeater#18]
I'm using this repeater and realy like it. But i'm trying to add data to the repeater dynamicly  (using javascript) in a sort of edit screen. But I can't figure out how to do it. Is there build in functionality to do this?

**Comment by DubFriend** [comment]
I decided not to add this feature.

One possible workaround here is to add dynamic information to each list item on the 

**show** configuration

```javascript
$('.repeater').repeater({
    show: function () {
        //add new data to the new item $(this)
    }
})
```
