### ISSUE TITLE
repeaterVal does not work.

### ISSUE THREAD

**Issue by Krloz4931** [DubFriend/jquery.repeater#19]
$('.repeater').repeaterVal()  does not work, it not exist as a function in jquery.repeater.js file.

TypeError: $(...).repeaterVal is not a function

**Comment by Xanvier54** [comment]
When I try the $('.repeater-default').repeaterVal(); on http://briandetering.net/repeater I get the same result.

**Comment by DubFriend** [comment]
Repeater Val was added relatively recently, (the version on http://briandetering.net/repeater is not up to date with this functionality).

Is it possible you are running an older version of jquery repeater that does not support repeaterVal?

**Comment by Krloz4931** [comment]
Hi DubFriend.

Thanks for response

Im using :
// jquery.repeater version 0.1.4
// https://github.com/DubFriend/jquery.repeater
// (MIT) 13-08-2014
// Brian Detering <BDeterin@gmail.com> (http://www.briandetering.net/)

downloaded from: https://plugins.jquery.com/repeater/

where can i find the lastest version ?

Thanks a lot :)

**Comment by Krloz4931** [comment]
Ahhh...!

Im sorry i newbie here on git :p

 i found the 1.1.3 version on code tab.

Thanks for all.

**Comment by DubFriend** [comment]
Last time I checked the jquery plugin registry was in read only mode, and I had been unable to publish new versions to the jquery page, so unfortunately the jquery registry is out of date :worried: 

Looks like you got things figured out tho :smiley:
