### ISSUE TITLE
defaultValues does not work with <input type="number" />

### ISSUE THREAD

**Issue by hguiney** [DubFriend/jquery.repeater#20]
https://jsfiddle.net/yth50vsf/

Console reports:

> Uncaught TypeError: Cannot read property 'set' of undefined

**Comment by DubFriend** [comment]
Ok, definitely a bug, I will look into this.

Thanks :smiley:

**Comment by hguiney** [comment]
Any update on this?

**Comment by DubFriend** [comment]
hey sorry, I've been consumed with other projects and let this fall to the wayside. Yea the "show" callback will provide the opportunity for workarounds.

If interested in a PR, the addition would be to the file `src/jquery.input.js` which creates a common interface for all the supported input types
