### ISSUE TITLE
Nesting of nested

### ISSUE THREAD

**Issue by Eldar-X** [DubFriend/jquery.repeater#21]
Hello! Is it possible to make chaining like this?
Repeater -> nested repeaters -> nested repeater

**Comment by DubFriend** [comment]
The code was designed to allow any level of nesting however I have not tested this.

So hopefully yes :smiley:

**Comment by Eldar-X** [comment]
I tried to do something like this

repeater: {
[0]->subRepeater: {name:'', subReapeter2:['']}
}

But I got

repeater: {
[0]->subRepeater: {name:''}
        subReapeter2:['']
}

**Comment by Eldar-X** [comment]
I think my problem is setting selector for sub nested elemenet

**Comment by DubFriend** [comment]
The configuration for two levels of nesting would look like this

```javascript
$('.repeater').repeater({
    repeaters: [{
        selector: '.inner-repeater',
        repeaters: [{ 
            selector: '.deep-inner-repeater' 
        }]
    }]
});
```

Where the selector is the jquery selector you would use to select each repeater.  Note that the selectors should be different at each level. (For example the selector for the outer repeater should not also select one of its inner repeaters)
