### ISSUE TITLE
jQuery(...).repeaterVal is not a function

### ISSUE THREAD

**Issue by surfget** [DubFriend/jquery.repeater#22]
Hello,
I would like to send the form data via ajax when the value of a field changes, so the user doesn't have to submit the form. For some reason I'm not able to make the repeaterVal function work. I always get the same error, repeaterVal is not a function.
I'm using version 0.1.5 with jQuery 1.11.3

Is it possible to do something like this?
```
jQuery('.single-field').live('change keyup',function(){ 
var values = jQuery('.repeater').repeaterVal();
});
```
Thank you!

**Comment by DubFriend** [comment]
the **repeaterVal** functionality was added pretty recently. Try updating to the latest version of **jquery.repeater**?
