### ISSUE TITLE
data-repeater-create not working

### ISSUE THREAD

**Issue by hatzipanis** [DubFriend/jquery.repeater#24]
I wanted to take advantage of `repeaterVal()` so I dropped in the latest version from this repo. Prior to that I had the plugin working fine using the older version on the jQuery website. 

Everything works fine with the new version except the `data-repeater-create` button no longer creates any repeating items. Everything else looks to be working: it's renaming the `name` attributes fine and I can delete the first row using `data-repeater-delete`. And it's throwing no console errors. 

Have you come across this issue before?

**Comment by hatzipanis** [comment]
I have recreated the issue here: http://jsbin.com/fuvuhutahe/edit?html,js,output

Please click 'Run with JS' before attempting. Deleting the item works but I cannot create a new one.

**Comment by DubFriend** [comment]
Hey thanks for the jsbin, this makes things easier.

looks like the problem is that the repeater method needs to be called on the immediate parent of the **data-repeater-list**

I changed the code to target the class **.jumbotron** instead of the class **.repeater**
[JSBin Here](http://jsbin.com/labegibali/edit?html,js,output)
```javascript
$(document).ready(function () {
	$('.jumbotron').repeater();
});
```

**Comment by Iamdamzy** [comment]
Hello, I'm having issues and I don't know how to go about it. I'm using angular data-ng-options to populate my select(dropdown) from the server and for everytime I try to Add(Repeat the Form), It does not populate the Items in the dropdown. Please how can I go about this. Thanks in Advance
