### ISSUE TITLE
nested repeater problem with FirstItemUndeletable

### ISSUE THREAD

**Issue by mohamedahmed1989** [DubFriend/jquery.repeater#25]
Hello, 

I'm having a problem with the repeater which lies in 
this option : isFirstItemUndeletable
when I activate the nested repeater it no longer works.  it doesn't work on nested elements 

Regards

**Comment by AlexandruDoda** [comment]
+1

**Comment by DubFriend** [comment]
Ok this is fixed in version **1.2.0** 🌮
