### ISSUE TITLE
"data-repeater-create" only works if a direct child of the repeater

### ISSUE THREAD

**Issue by AlexandruDoda** [DubFriend/jquery.repeater#26]
Hey,

I have an issue with the "data-repeater-create" button - it doesn't work if I put it anywhere inside the repeater other than as a direct child of the repeater. I am trying to create a certain table-style layout and have the add button like this:

![screen shot 2016-09-25 at 10 12 37](https://cloud.githubusercontent.com/assets/8274669/18814127/a586d9e0-8308-11e6-9157-91cbb0716bac.png)

The output should look something like this:
![screen shot 2016-09-25 at 10 16 04](https://cloud.githubusercontent.com/assets/8274669/18814140/18e1c03a-8309-11e6-9193-1da7fc2a43b2.png)

I presume it's because the repeater is looking for the create button only as a direct child. Perhaps make it find it anywhere inside the repeater?

**Comment by BabyDino** [comment]
I have the same issue.

**Comment by DubFriend** [comment]
Hey I should be able to put in a fix this weekend. Thanks :beer:

**Comment by DubFriend** [comment]
Ok released a new version **1.1.4** that should fix this case.

The existing version **1.1.3** should also work if you put the **repeater** class on the table element.

```html
<table class="table repeater">
  ...
</table>
```
