### ISSUE TITLE
Initialising an empty repeater

### ISSUE THREAD

**Issue by AlexandruDoda** [DubFriend/jquery.repeater#28]
Is there any way to make sure a repeater or nested repeater is initialised without any starter element? I just want the repeater to show the "Add" button and let the user decide whether he needs it or not. Currently, a set of fields is there by default.

**Comment by DubFriend** [comment]
The library builds a template from the starter element and uses this to build new elements, so the html needs to be there.

One way you could work around this is by setting the starter elements style to **display:none**, and then using the custom show element to remove this property when new elements are created.

Something like:

```html
<form class="repeater">
    <div data-repeater-list="group-name">
      <div data-repeater-item style="display:none;">
        <input type="text" name="text-input" value="A"/>
        <input data-repeater-delete type="button" value="Delete"/>
      </div>
    </div>
    <input data-repeater-create type="button" value="Add"/>
</form>
```

```js
$('.repeater').repeater({
  show: function () {
    $(this).show();
  }
});
// you can delete the first element after the repeater has been initialized 
// (it has stored the template in its own memory)
$('.repeater').find('[data-repeater-delete]').click();
```

**Comment by AlexandruDoda** [comment]
Thanks for the tip ^_^ Perhaps it would be nice if implemented as a native setting? Could also do something like after initialization, it calls $(this).remove() or something.

Cheers!
Alexandru

**Comment by DubFriend** [comment]
Yea I think your right this setting probably belongs in the library, I will work on putting this in (probably tonight).

**Comment by DubFriend** [comment]
Ok this is in on version **1.1.5**.

Set your first (and only) **data-repeater-item** to `style="display:none;"` and pass the flag
`initEmpty: true` in the configuration

```html
<form class="repeater">
    <div data-repeater-list="group-name">
      <div data-repeater-item style="display:none;">
        ...
      </div>
    </div>
    <input data-repeater-create type="button" value="Add"/>
</form>
```

```js
$('.repeater').repeater({ initEmpty: true });
```

**Comment by KrunchMuffin** [comment]
When I have existing items, those are getting hidden as well as the blank option. I only put the hidden in the template item.

**Comment by defunct5** [comment]
It all fits together https://hypertexter.space/questions/conceal-the-div-elements-when-the-variable-value-is-devoid-of-content
