### ISSUE TITLE
Getting the subject repeater

### ISSUE THREAD

**Issue by AlexandruDoda** [DubFriend/jquery.repeater#32]
Hey man :)

Is there any way to pull the repeater that is being affected on show and on hide? I am trying to create a script that does a scroll animation to the top of the repeater when an element is added or removed. I tried passing a variable as a parameter to the show and hide functions but it didn't work.

Cheers!
Alexandru

**Comment by DubFriend** [comment]
Not sure I understand exactly.

the show and hide methods "this" value is set to the newly created item, not sure if that helps?

```js
$('.repeater').repeater({
  show: function () {
    // "this" is the new item being shown
    $(this)
  }
})
```

**Comment by AlexandruDoda** [comment]
Right, so something like that, but to target the repeater itself instead, not the item that is being shown.

**Comment by DubFriend** [comment]
Wouldn't this work?

```js
$('#repeater').repeater({
  show: function () {
    // you could get a reference to whatever else you need here as well
    $('body').scrollTo('#repeater');
  }
})
```

**Comment by AlexandruDoda** [comment]
Unfortunately not because I have multiple repeaters on the same page and it wouldn’t know how to target each individually.

**Comment by DubFriend** [comment]
you could give each a unique attribute so they could be targeted with different jquery css selectors?

```html
<div id="repeater-1">...</div>
<div id="repeater-2">...</div>
```

```js
$('#repeater-1').repeater();
$('#repeater-2').repeater();
```

or if that is impractical 

```js
$('.repeater').repeater({
  show: function () {
    // closest walks up the dom tree untill it first finds a matching element
    $(this).closest('.repeater');
  }
})
```

or get store a reference directly

```js
var $repeater = $('.repeater');
$repeater.repeater({
  show: function () {
    $('body').scrollTo($repeater);
  }
});
```
