### ISSUE TITLE
Jumping to top of screen with nested repeater

### ISSUE THREAD

**Issue by lumpysimon** [DubFriend/jquery.repeater#37]
Hi

I've set up a two-level repeater (top level are 'questions', inner level are 'choices'). All is working well except for one thing: when you click an `Add Choice` or `Delete Choice` button on any question apart from the first one, it correctly adds or deletes the choice, but then jumps to the top of the screen. So you then have to scroll back down to the correct place every time (which in my case is below lots of other stuff, so it's a lot of jumping about and scrolling).

The same thing happens with `Delete Question`, again it's for any question except the first one.

The `Add Question` button is fine.

**Comment by lumpysimon** [comment]
Very sorry to hassle you, I wondered if there's any update on this? Happy to help out if there's anything I can do to help clarify/debug/test/etc (I'm a developer but I'm not a JavaScript expert).

**Comment by siokoden** [comment]
Check your delete button, it must have href = "#", change it for href = "javascript:;"

**Comment by lumpysimon** [comment]
Ah, something so simple!

Thanks very much, it's working perfectly now.
