### ISSUE TITLE
Question: flagging items to prevent deletion?

### ISSUE THREAD

**Issue by flashadvocate** [DubFriend/jquery.repeater#39]
Just wondering if there's a mechanism in place for hiding the delete button for items containing a specific class or data value. I have a use case which includes several items that need to persist in addition to any extra values a user might want to add.

I can dig through the library to answer this question, but on the off chance that you save me the time of looking, or doing something custom myself. :)

**Comment by DubFriend** [comment]
yea nothing like this, but the custom "show" callback might be a decent place to hook something up

```javascript
$('.my-repeater').repeater({
  show: function () {
    if(shouldBeHidden(this)) {
      $(this).find('[data-repeater-delete]').hide();
    }
    $(this).show();
  }
})
```
