### ISSUE TITLE
Repeater for Labels

### ISSUE THREAD

**Issue by bob-zs** [DubFriend/jquery.repeater#40]
Is there a way for the repeater to also repeat labels with their corresponding checkboxes?

```html
<input type="checkbox" id="myCheckbox[0]"><label for="myCheckbox[0]"></label>
```
repeated to
```html
<input type="checkbox" id="myCheckbox[1]"><label for="myCheckbox[1]"></label>
```

**Comment by DubFriend** [comment]
you could use a custom "show" callback to do this, something like this?
```javascript
$('.my-repeater').repeater({
  show: function () {
    $(this).find('label').attr('for', $(this).find('input').attr('id'));
    $(this).show();
  }
})
```

**Comment by juancarlosestradanieto** [comment]
Hi, I just made this, I hope it can help anybody.
This plugin is very helpful. Thanks.
`
$('.my-repeater').repeater({
  show: function () {

	//fixing the issue of the labels
	var params = [this];
	$(this).find("label[for]").each(function(index, element) {
		var currentRepeater = params[0];
		var originalFieldId = $(element).attr("for");
		var newField = $(currentRepeater).find("input[id='"+originalFieldId+"']");
		if($(newField).length > 0)
		{
			var newFieldName = $(newField).attr('name');
			$(newField).attr('id', newFieldName);
			$(currentRepeater).find("label[for='"+originalFieldId+"']").attr('for', newFieldName);
		}
	},params);					
	
	//showing the new repeater
	$(this).slideDown();

    $(this).show();
  }
})
`

**Comment by martinmurciego** [comment]
```
$('.my-repeater').repeater({
show: function () {

//fixing the issue of the labels
var params = [this];
$(this).find("label[for]").each(function(index, element) {
	var currentRepeater = params[0];
	var originalFieldId = $(element).attr("for");
	var newField = $(currentRepeater).find("input[id='"+originalFieldId+"']");
	if($(newField).length > 0)
	{
		var newFieldName = $(newField).attr('name');
		$(newField).attr('id', newFieldName);
		$(currentRepeater).find("label[for='"+originalFieldId+"']").attr('for', newFieldName);
	}
},params);					

//showing the new repeater
$(this).slideDown();

$(this).show();
}
})
```

**Comment by helloKeyur** [comment]
> ou could use a custom "show" callback to do this, something like this?

How I can set my ID attribute in input box ??

**Comment by helloKeyur** [comment]
> Is there a way for the repeater to also repeat labels with their corresponding checkboxes?
> 
> ```
> <input type="checkbox" id="myCheckbox[0]"><label for="myCheckbox[0]"></label>
> ```
> 
> repeated to
> 
> ```
> <input type="checkbox" id="myCheckbox[1]"><label for="myCheckbox[1]"></label>
> ```

hello @bob-zs please help me 
How I can increase my input ID Attribute using this formRepeater plugin?

**Comment by cawecoy** [comment]
@DubFriend thanks. What if some item is deleted and then the list gets reordered?

**Comment by DubFriend** [comment]
Not sure, try it and find out?
