### ISSUE TITLE
Multiple repeater-lists in single form

### ISSUE THREAD

**Issue by bahriddin** [DubFriend/jquery.repeater#41]
Imagine I have a form named vehicles and I should have 2 repeater lists: trucks and cars. But when I create them, the second one's buttons (add and delete) are not working properly. Please help to fix it a.s.a.p. My project is depending on your help!

**Comment by bahriddin** [comment]
Oh I found 1 solution: I need to remove repeater class from form and add this class to every lists' parent element e.g. div.

**Comment by FloresNelson** [comment]
@bahriddin Could you please share your code? I'm trying to achieve the same but the solution you described is not working for me.

**Comment by bahriddin** [comment]
@FloresNelson It was a long time ago. The only thing I could remember, go for the more common div and it should work as you wish. I hope author might help.
Sorry about that.
