### ISSUE TITLE
Select2 Ajax dropdown Bugs

### ISSUE THREAD

**Issue by TnCoders** [DubFriend/jquery.repeater#44]
Hi,  We have problem working with Select2 using jquery Repeater.

When clicking on button "Add" to repeat the form, the select2 dropdown is not working it's not initialised. how we can do this ?

**Comment by heohni** [comment]
HI, I have the same issue! Did you already found a solution?

**Comment by TnCoders** [comment]
No sorry heohni i was forced to pass the amount of reapter in the url and create them in PHP without jquery ;:( if you found a solution please post it here

**Comment by viveroni** [comment]
`show: function () {
        $(this).find('.chosen').chosen({
          width: "100%",
          disable_search: true
        });
        $(this).slideDown();
      }`

**Comment by DubFriend** [comment]
Yea the library isnt well designed for some of the more exotic input types. But as viveroni points out, the on "show" callback gives you a hook to patch things up, and add your own custom behavior.

Just to clarify, the value of "this" in the "show" callback is a reference to the html element of the newly created item.
