### ISSUE TITLE
accept configuration options

### ISSUE THREAD

**Issue by mnbob70** [DubFriend/jquery.repeater#5]
I'd like to suggest that you add some configuration options. In particular an option to not allow a user to delete the first item. If that option is specified then hide the first data-repeater-delete item:
<code>$list.find('[data-repeater-item]').first().find('[data-repeater-delete]').hide();</code>

**Comment by DubFriend** [comment]
Hey that is a good idea, I should be able to put that in tonight!

**Comment by DubFriend** [comment]
Sorry I didnt get around to this till now.  The config option `isFirstItemUndeletable` is now available.

```javascript
QUnit.test('isFirstItemUndeletable configuration option', function (assert) {
    this.$repeater.repeater({ isFirstItemUndeletable: true });

    var $firstDeleteButton = this.$repeater.find('[data-repeater-item]')
                                        .first().find('[data-repeater-delete]');

    assert.strictEqual($firstDeleteButton.length, 0, 'first delete button is removed');
});
```
