### ISSUE TITLE
Select2 input fields are not working as repeater fields.

### ISSUE THREAD

**Issue by AnwerAR** [DubFriend/jquery.repeater#51]
I am using jQuery repeater and select2.js in a project. they both are working fine separately however when i use a select2 dropdown field inside repeater the select2 dropdown field is showing but the dropdown options are not appearing thus jQuery Repeater is not working with select2.js. 

it will be great if there's any fix for this issue? Thank you

**Comment by DubFriend** [comment]
The library doesn't support this out of the box but you could probably make it work using the show callback

```js
$('.my-repeater').repeater({
  show: function () {
    // the value of "this" is set to the newly created html element
    setNewElementWithMyCustomBehavior(this)
  }
})
```

**Comment by AnwerAR** [comment]
Thank you for your response. show callback was not enough in my cae. i've hooked my function in index callback too.

**Comment by AnwerAR** [comment]
is there an option to set min and max repeater rows?

**Comment by sajadabasi** [comment]
is there an option to set min and max repeater rows?
