### ISSUE TITLE
setList doesn't work for select tags

### ISSUE THREAD

**Issue by NinaArens** [DubFriend/jquery.repeater#57]
I'm using a repeater with several select tags. I'd like to load in a row and mark items as selected in each select tag through the selectList function but this seems to not be working.

This is my HTML for the repeated line:
`                                <div data-repeater-item style="display:none;">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <select class="form-control ddlField1" id="ddlField1" runat="server" DataTextField="Name" name="ddlField1">
                                            </select>
                                        </div>
                                        <div class="col-md-3">
                                            <select class="form-control ddlOperator1" id="ddlOperator1" runat="server" DataTextField="Name" name="ddlOperator1">
                                            </select>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group form-md-line-input" style="padding-top: 0px;">
                                                <input type="text" class="form-control txtValue1" runat="server" id="txtValue1" name="txtValue1" />
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <button data-repeater-delete type="button" class="btn red"><i aria-hidden="true" class="icon-close"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
`
And this is the javascript:
`            $repeater.setList([
                    {
                       'ctl00$cph_body$ddlField1': '43'
                    }
                ]);`

If I change ddlField1 to txtValue1 it will put the value in that textbox. But no such luck for the select.

**Comment by FernandoGOT** [comment]
+1
