### ISSUE TITLE
input type "tel"

### ISSUE THREAD

**Issue by JonCatmull** [DubFriend/jquery.repeater#6]
input type "tel" throw a not a valid input type error

**Comment by JonCatmull** [comment]
Added roughly this and it fixed it for me

line 292:

var createInputTel = function (fig) {
    var my = {},
        self = createInputText(fig, my);

    self.getType = function () {
        return 'tel';
    };

    return self;
};

line 529: 

         tel: createInputTel,

line 598: 
        else if($self.is('input[type="tel"]')) {
            addInputsBasic('tel', $self);
        }

line 640:

        addInputsBasic('tel', 'input[type="tel"]');

**Comment by DubFriend** [comment]
Hey thanks, could you make a pull request for this?

**Comment by camiloclc** [comment]
I'm also having issues with this, but when using type number. Seems like a few types have not been implemented.

**Comment by DubFriend** [comment]
I will work on a fix to support all the various input types.  When that is in I will comment/close this issue and bump the version.

**Comment by camiloclc** [comment]
Thanks! It's a great library, saved me many hours of work!

**Comment by DubFriend** [comment]
Ok I put in a fix for this in this commit 82246bf0b55105d4f3963499c87411bc9e2d92e3 and bumped the version **1.0.2**

The library will treat all unhandled input types as a "text" input type, which I believe should be compatible with most or all of the input types that are not being explicitly handled.

**Comment by JonCatmull** [comment]
Great thanks
