### ISSUE TITLE
Multiple selects on one page

### ISSUE THREAD

**Issue by JonCatmull** [DubFriend/jquery.repeater#7]
$('[data-repeater-list]').parent().repeater({
    // options
});

This is the cleanest way I found to implement multiple repeaters on one page, might be worth adding to readme.

And if possible modify code to work without needing to target parent because if  2 repeater lists share a parent probably only the second will work.

But that aside nice plugin : )

**Comment by DubFriend** [comment]
If you are not running version 1.0.1 try this first as this issue was addressed a while ago.

You should be able multiple repeaters like this.

```html
<div class="repeater">...</div>
<div class="repeater">...</div>
<script>
$('.repeater').repeater({})
</script>
```
Or if you want to differentiate between repeaters
```html
<div class="repeater-a">...</div>
<div class="repeater-b">...</div>
<script>
$('.repeater-a').repeater({});
$('.repeater-b').repeater({});
</script>
```

Let me know if this does not help.
