### ISSUE TITLE
Does this work with drag-and-drop reordering?

### ISSUE THREAD

**Issue by jordanlev** [DubFriend/jquery.repeater#9]
Hi, this looks like a really useful library. A question for you: will this work if I allow users to re-order the items via drag and drop (for example, with the jquery UI "sortable" plugin)? I understand that the actual drag-drop functionality isn't part of this library, but I wonder if the re-ordering would mess up the id numbers or anything like that?

Thanks!

**Comment by DubFriend** [comment]
Hmm, yea the indexes would not be reordered after a drag and drop event. However I could expose a method that allows you to manually trigger a reordering of the indexes. You could then call this method after a user does a drag and drop.

**Comment by DubFriend** [comment]
Ok, put in a **ready** callback that passes a **setIndexes** method as its first argument.

So with the latest version **1.2.0** you should be able to manually reindex like this

```javascript
$('.repeater').repeater({
    ready: function (setIndexes) {
        $dragAndDrop.on('drop', setIndexes);
    }		
})
```

26a44e94a34b4f4dfab183dcac5930576e9048af
